@host = http://localhost:8080
#@host = http://api.server.pl

//--------------------------------------------------------- Login

POST {{host}}/auth/login/ HTTP/1.1
content-type: text/plain

{ "user": "user", "password": "sqrt" }
### Login by JSON

POST {{host}}/auth/login/ HTTP/1.1
content-type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="user"

admin
--boundary
Content-Disposition: form-data; name="password"

sqrt
### Login by FORM

//--------------------------------------------------------- Logout

POST {{host}}/auth/logout/ HTTP/1.1
### Logout

//--------------------------------------------------------- Create

POST {{host}}/auth/create/ HTTP/1.1
content-type: text/plain

{ "user": "newuser", "email": "newemail@sqrt.pl", "password": "MyP@ssw0rd" }
### Create new user
