@host = http://localhost:8080
#@host = http://api.server.pl

//----------------------------------------------- Login

POST {{host}}/auth/login/ HTTP/1.1
content-type: text/plain

{ "user": "admin", "password": "p@ssWd40" }
### authorization as admin

POST {{host}}/auth/logout/ HTTP/1.1
### logout

//----------------------------------------------- GET File

GET {{host}}/file/lab/keypoints.csv HTTP/1.1
### get FILE '~/lab/keypoints.csv'